#!/bin/bash

#
# server
export PORT=8080

#
# redis
export REDIS_HOST=localhost
export REDIS_PORT=6379

version=$(cat version.sbt|awk -F "\"" '{print($2)}')

java -jar target/scala-2.13/fragnostic-i18n-server-project_2.13-$version.jar 

